export const productData = [
  {
    id: 1,
    image: require('@/assets/images/image(1).png'),
    subImages: [
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
    ],
    title: 'Modern Sofa',
    favorites: 34,
    amount: '$230.00',
    stock: 12,
    description: 'A sleek, modern sofa that fits perfectly in any contemporary living room. Designed with comfort and style in mind.',
    discount: 10,
    similar: [
      {
        id: 4,
        image: require('@/assets/images/image(1).png'),
        title: 'Floor Vase',
        favorites: 18,
        amount: '$40.00',
        stock: 6,
      },
      {
        id: 2,
        image: require('@/assets/images/image(1).png'),
        title: 'Wooden Desk',
        favorites: 21,
        amount: '$180.00',
        stock: 5,
      },
       {
        id: 8,
        image: require('@/assets/images/image(1).png'),
        title: 'Floor Vase',
        favorites: 18,
        amount: '$40.00',
        stock: 6,
      },
      {
        id: 1,
        image: require('@/assets/images/image(1).png'),
        title: 'Wooden Desk',
        favorites: 21,
        amount: '$180.00',
        stock: 5,
      },
    ],
  },
  {
    id: 2,
    image: require('@/assets/images/image(1).png'),
    subImages: [
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
    ],
    title: 'Wooden Desk',
    favorites: 21,
    amount: '$180.00',
    stock: 5,
    description: 'Crafted from solid oak, this desk brings a rustic charm to your home office or workspace.',
    discount: 5,
    similar: [
      {
        id: 3,
        image: require('@/assets/images/image(1).png'),
        title: 'Reading Lamp',
        favorites: 56,
        amount: '$75.00',
        stock: 9,
      },
    ],
  },
  {
    id: 3,
    image: require('@/assets/images/image(1).png'),
    subImages: [
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
    ],
    title: 'Reading Lamp',
    favorites: 56,
    amount: '$75.00',
    stock: 9,
    description: 'An adjustable reading lamp with a minimalistic design. Perfect for your bedside or study corner.',
    discount: 15,
    similar: [
      {
        id: 5,
        image: require('@/assets/images/image(1).png'),
        title: 'Reading Lamp',
        favorites: 56,
        amount: '$75.00',
        stock: 9,
      },
    ],
  },
  {
    id: 4,
    image: require('@/assets/images/image(1).png'),
    subImages: [
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
    ],
    title: 'Floor Vase',
    favorites: 18,
    amount: '$40.00',
    stock: 6,
    description: 'Elegant floor vase to elevate your home decor with a modern yet timeless feel.',
    discount: 0,
    similar: [
      {
        id: 6,
        image: require('@/assets/images/image(1).png'),
        title: 'Floor Vase',
        favorites: 18,
        amount: '$40.00',
        stock: 6,
      },
    ],
  },
  {
    id: 5,
    image: require('@/assets/images/image(1).png'),
    subImages: [
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
    ],
    title: 'Reading Lamp',
    favorites: 56,
    amount: '$75.00',
    stock: 9,
    description: 'Compact and stylish, this reading lamp enhances your lighting setup without overwhelming the space.',
    discount: 8,
    similar: [
      {
        id: 3,
        image: require('@/assets/images/image(1).png'),
        title: 'Reading Lamp',
        favorites: 56,
        amount: '$75.00',
        stock: 9,
      },
    ],
  },
  {
    id: 6,
    image: require('@/assets/images/image(1).png'),
    subImages: [
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
      require('@/assets/images/image(1).png'),
    ],
    title: 'Floor Vase',
    favorites: 18,
    amount: '$40.00',
    stock: 6,
    description: 'Stylish ceramic floor vase, adds a pop of elegance to your hallway or living space.',
    discount: 12,
    similar: [
      {
        id: 1,
        image: require('@/assets/images/image(1).png'),
        title: 'Modern Sofa',
        favorites: 34,
        amount: '$230.00',
        stock: 12,
      },
    ],
  },
];
